### PR TITLE
Fixup: PATH_SAFE

### LINKED ISSUE #290: Fixup w.r.PATH_SAFE to match RFC3986
Related to discussion in https://github.com/Pylons/pyramid/pull/2811.

### PR DESCRIPTION
**Pull request by bertjwregeer**
This fixes PATH_SAFE to include more of the safe characters from RFC3986.

Closes #290

### CODE REVIEW

**Comment by mmerickel** [comment]
You left a few characters (like `_`) out according to https://github.com/Pylons/pyramid/pull/2811. Any particular reason?

**Comment by bertjwregeer** [comment]
Yes:

`urllib.parse.quote`:

> Replace special characters in string using the %xx escape. Letters, digits, and the characters '_.-' are never quoted.

https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote

**Comment by mmerickel** [comment]
Great, thanks.

**Comment by bertjwregeer** [comment]
Update the only existing test :P

**Pull request merged**
