### PR TITLE
Remove headers length from content part if present (python issue 27777)

### PR DESCRIPTION
**Pull request by julienmeyer**
Apply python issue https://bugs.python.org/issue27777

### CODE REVIEW

**Comment by bertjwregeer** [comment]
The stacktrace included with that Python issue doesn't show `read_multi` in it at all... how does removing the content-length header from the environ affect how it parses multi-part messages?

**Comment by bertjwregeer** [comment]
Are you instead referring to this issue: https://bugs.python.org/issue24764?

**Comment by julienmeyer** [comment]
You are right but the first issue has also the same type of problem.

In my case, I'm using Retrofit (Android application) and Pyramid on the back-end. 
Retrofit set by default the content-length on each part of the form content and when this field is set, cgi process the data as bytes and not str...

With Python 3.5 the problem is solved because content-length header field is removed by the read_multi function from cgi module.

**Comment by bertjwregeer** [comment]
The first issue is separate from the issue I linked. As in, if you are hitting the first issue the patch you provided does not actually fix the issue.

**Comment by julienmeyer** [comment]
After taking a look on the retrofit request sent by my application (a mix of files and string comments), my problem comes from issue 24764 and not 27777 as I have first think. 
Sorry for the mistake.

**Comment by bertjwregeer** [comment]
I submitted a patch to 27777 which actually fixes both 24764 and 27777. I will add that fix to WebOb, since no Python version has this fix yet.

**Comment by bertjwregeer** [comment]
I've created PR #294 for this issue. Thanks for bringing this to my attention.

**Pull request closed without merging**
