### PR TITLE
rename "master" to "main"

### PR DESCRIPTION
**Pull request by jvanasco**

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]

**Comment by stevepiercy** [comment]
Build error: https://github.com/Pylons/webob/actions/runs/3482170298/jobs/5824179906#step:5:40

Would you please fix this in the `conf.py`? Then it should pass.

**Review by stevepiercy — APPROVED** [review]
All green now. Thank you!

**Comment by jvanasco** [comment]
Thank YOU for walking me through this!

**Comment by bertjwregeer** [comment]
Thank you!

**Pull request merged**
