### PR TITLE
Allow content-length to be unset with app_iter

### PR DESCRIPTION
**Pull request by greghaynes**
When using an app_iter it is sometimes desireable to not set
content-length (if you, for example, do not know what your content
length is).

### CODE REVIEW

**Comment by bertjwregeer** [comment]
This looks good. I'll write a test that covers the now missing line in `byterange.py`.

**Comment by greghaynes** [comment]
It just occurred to me that this breaks with an open ended range request (where range.end is None).  I'll make a test for that too.

**Comment by bertjwregeer** [comment]
I hadn't thought about that. I was going to dive into the RFC's and read up on the range headers to better understand all of the different scenarios.

**Comment by greghaynes** [comment]
Ah, well there is a big rabbit hole. Another case is that you can define multiple ranges. AFAICT that is not supported at all by our current range.parse implementation.

**Comment by bertjwregeer** [comment]
That whole logic is a huge mess, we are also re-creating the Request from the environ a second time just to be able to get the range that was requested because the new Response does not get the original Request.

I feel like the conditional response doesn't really belong in WebOb, but instead the web server should take the response and change it as necessary to satisfy the client. At this point we are stuck with it.

**Comment by bertjwregeer** [comment]
@greghaynes Have you made any further progress on this? I'd like outside input on what people would like moving forward...

**Comment by bertjwregeer** [comment]
I'm closing this for now. If you'd like to re-open with an updated implementation I'd be happy to review it.

**Pull request closed without merging**
