### PR TITLE
Use _MiddlewareFactory as decorator with arguments

### PR DESCRIPTION
**Pull request by renyidong**
This change allows _MiddlewareFactory to be used as decorator with argument:
```
@wsgify.middleware
def restrict_ip(req, app, ips):
    if req.remote_addr not in ips:
        raise webob.exc.HTTPForbidden('Bad IP: %s' % req.remote_addr)
    return app

@restrict_ip(ips=['127.0.0.1'])
@wsgify
def app(req):
      return 'hi'
```

### CODE REVIEW

**Comment by mmerickel** [comment]
@renyidong Could you update this PR with a test case showing your intended workflow? I think the idea itself is fine!

**Comment by renyidong** [comment]
@mmerickel Taking the example from http://docs.webob.org/en/latest/api/dec.html
```
@wsgify.middleware
def restrict_ip(req, app, ips):
    if req.remote_addr not in ips:
        raise webob.exc.HTTPForbidden('Bad IP: %s' % req.remote_addr)
    return app

@wsgify
def app(req):
    return 'hi'

wrapped = restrict_ip(app, ips=['127.0.0.1'])
```
I have to define an extra function and wrap it with the middleware. 

With this patch, I would be able to achieve same effect as the example at very beginning.

**Comment by mmerickel** [comment]
@renyidong I understand the patch. I was asking if you could please add a test case to the codebase to ensure this keeps working in the future.

**Comment by renyidong** [comment]
@mmerickel Apologies for my misinterpret. I appended test code to `test_middleware()`. Or you would prefer adding a separate test?

**Comment by bertjwregeer** [comment]
A separate test would be preferred. Thanks!

**Comment by renyidong** [comment]
@bertjwregeer Let me know if there is anything else you need.

**Comment by mmerickel** [comment]
LGTM!

**Comment by bertjwregeer** [comment]
Sorry for taking so long! I've merged this into master.

**Pull request merged**
